import Link from 'next/link'
import {notFound,redirect} from 'next/navigation'
import AppShell from '@/components/AppShell'
import {getSession} from '@/lib/auth'
import {prisma} from '@/lib/prisma'
import {eur,dateFr} from '@/lib/format'
import {ArrowLeft,Printer,RotateCcw,ShieldCheck} from 'lucide-react'

export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{refund?:string}>}){
 const s=await getSession();if(!s)redirect('/login');const {id}=await params;const sp=await searchParams
 const sale=await prisma.posSale.findUnique({where:{id},include:{items:true,refunds:{orderBy:{createdAt:'desc'}}}});if(!sale)notFound()
 const remaining=Math.max(0,Number(sale.total)-Number(sale.refundedAmount))
 return <AppShell><div style={{maxWidth:1100,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:16}}><div><Link href="/pos/sales" className="back"><ArrowLeft size={16}/> Retour aux ventes</Link><div className="eyebrow" style={{marginTop:12}}>VENTE POS · V15</div><h1 style={{margin:'4px 0'}}>Ticket #{sale.receiptNo}</h1><p style={{margin:0,color:'#7d8998',fontSize:10}}>{dateFr(sale.createdAt)} · {sale.cashierName}{sale.customerName?` · ${sale.customerName}`:''}</p></div><Link className="btn secondary" href={`/pos/receipt/${sale.id}`} target="_blank"><Printer size={16}/> Ticket</Link></div>
  {sp.refund==='ok'&&<div className="success-box" style={{marginBottom:12}}>Remboursement enregistré.</div>}
  <div className="detail-grid"><section className="stack"><div className="card"><div className="section-title"><div><h2>Articles</h2><p>Détail de la vente.</p></div><strong>{eur(Number(sale.total))}</strong></div><div className="table-wrap"><table><thead><tr><th>Article</th><th>Qté</th><th>Prix</th><th>Total</th></tr></thead><tbody>{sale.items.map(i=><tr key={i.id}><td>{i.name}<small className="cell-sub">{i.sku}</small></td><td>{i.quantity}</td><td>{eur(Number(i.unitPrice))}</td><td>{eur(Number(i.lineTotal))}</td></tr>)}</tbody></table></div><div style={{marginTop:12}}><div className="money-line"><span>Sous-total</span><strong>{eur(Number(sale.subtotal))}</strong></div><div className="money-line"><span>Remise ({Number(sale.discountPercent).toFixed(1)}%)</span><strong>- {eur(Number(sale.discountAmount))}</strong></div><div className="money-line due"><span>Total</span><strong>{eur(Number(sale.total))}</strong></div><div className="money-line"><span>Déjà remboursé</span><strong>{eur(Number(sale.refundedAmount))}</strong></div><div className="money-line"><span>Reste remboursable</span><strong>{eur(remaining)}</strong></div></div></div>
  <div className="card"><div className="section-title"><div><h2>Historique remboursements</h2></div></div>{sale.refunds.length?<div className="payment-list">{sale.refunds.map(r=><div key={r.id}><div><b>- {eur(Number(r.amount))}</b><small>{r.method} · {dateFr(r.createdAt)} · {r.createdBy}</small></div><span>{r.reason}{r.restock?' · stock remis':''}</span></div>)}</div>:<div className="empty compact-empty">Aucun remboursement.</div>}</div></section>
  <aside className="stack"><div className="card"><div className="section-title"><div><h2><RotateCcw size={18}/> Rembourser</h2><p>Contrôle administrateur.</p></div></div>{s.role==='ADMIN'&&remaining>0?<form className="mini-form" action={`/api/pos/sales/${sale.id}/refund`} method="post"><input name="amount" type="number" step="0.01" min="0.01" max={remaining} defaultValue={remaining.toFixed(2)} required/><select name="method" defaultValue={sale.paymentMethod}><option value="CARD">Carte</option><option value="CASH">Espèces</option><option value="TRANSFER">Virement</option><option value="OTHER">Autre</option></select><input name="reason" placeholder="Motif du remboursement" required/><label style={{display:'flex',gap:8,alignItems:'center',fontSize:9}}><input type="checkbox" name="restock"/> Remettre le stock (uniquement remboursement total)</label><button className="btn"><RotateCcw size={15}/> Valider le remboursement</button></form>:<div className="warn"><ShieldCheck size={16}/><div><b>{remaining<=0?'Vente entièrement remboursée':'Accès administrateur requis.'}</b></div></div>}</div></aside></div>
 </div></AppShell>
}
