'use client'

import {useMemo,useState} from 'react'
import {AlertTriangle, ArrowLeft, ArrowRight, BatteryCharging, Camera, Check, CircleUserRound, ClipboardCheck, DatabaseBackup, Euro, FileSignature, Gauge, HardDrive, ImagePlus, Mail, MessageCircle, Package, Phone, Search, ShieldCheck, Smartphone, Tablet, Trash2, UserPlus, Watch, Wrench, Gamepad2, Laptop, Droplets, Power} from 'lucide-react'
import {modelsForBrand,smartphoneBrands} from '@/lib/smartphoneCatalog'

type ClientLite={id:string;name:string;phone:string;email:string|null}
type UserLite={id:string;name:string;role:string}
type Priority='BASE'|'NORMAL'|'HIGH'|'URGENT'
type Category='SMARTPHONE'|'TABLET'|'LAPTOP'|'CONSOLE'|'WATCH'|'OTHER'
type Contact='SMS'|'WHATSAPP'|'EMAIL'|'PHONE'
type PhotoItem={name:string;dataUrl:string}

const priorityMeta:Record<Priority,{label:string;desc:string;className:string}>={
 BASE:{label:'Basse',desc:'Peut attendre',className:'low'}, NORMAL:{label:'Normale',desc:'Flux standard',className:'normal'}, HIGH:{label:'Haute',desc:'À prioriser',className:'high'}, URGENT:{label:'Urgente',desc:'Traitement immédiat',className:'urgent'},
}
const cats:[Category,string,any][]=[['SMARTPHONE','Téléphone',Smartphone],['TABLET','Tablette',Tablet],['LAPTOP','Ordinateur',Laptop],['CONSOLE','Console',Gamepad2],['WATCH','Montre',Watch],['OTHER','Autre',Package]]
const checklistOptions=['Écran / vitre','Châssis / coque','Caméras','Boutons','Connecteur charge','Haut-parleurs','Microphones','Wi‑Fi / Bluetooth','Face ID / empreinte','Traces d’oxydation']

export default function IntakeWizard({clients,team}:{clients:ClientLite[];team:UserLite[]}){
 const [step,setStep]=useState(1),[clientId,setClientId]=useState(''),[query,setQuery]=useState(''),[newClient,setNewClient]=useState(false)
 const [priority,setPriority]=useState<Priority>('NORMAL'),[category,setCategory]=useState<Category>('SMARTPHONE'),[contact,setContact]=useState<Contact>('SMS')
 const [photos,setPhotos]=useState<PhotoItem[]>([]),[checks,setChecks]=useState<string[]>([])
 const [form,setForm]=useState({clientName:'',phone:'',email:'',address:'',postalCode:'',city:'',brand:'Apple',model:'',color:'',storage:'',imei:'',lockCode:'',conditionIn:'',accessories:'',issue:'',diagnosticNote:'',notes:'',total:'0',deposit:'0',paymentMethod:'CARD',promisedAt:'',warrantyDays:'90',assignedToId:'',signature:'',powersOn:'yes',moisture:'no',backup:'yes',dataAccess:'no',quoteRequired:'yes'})
 const selected=clients.find(c=>c.id===clientId),set=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v}))
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return clients.slice(0,10);return clients.filter(c=>`${c.name} ${c.phone} ${c.email||''}`.toLowerCase().includes(q)).slice(0,10)},[clients,query])
 const smartphoneModels=useMemo(()=>modelsForBrand(form.brand),[form.brand])
 function chooseClient(c:ClientLite){setClientId(c.id);setNewClient(false);setQuery(c.name);setForm(v=>({...v,clientName:c.name,phone:c.phone,email:c.email||''}))}
 function clearClient(){setClientId('');setQuery('');setForm(v=>({...v,clientName:'',phone:'',email:''}))}
 function canNext(){if(step===1)return !!(clientId||(form.clientName.trim()&&form.phone.trim()));if(step===2)return !!(form.brand.trim()&&form.model.trim());if(step===3)return !!form.issue.trim();return true}
 async function addPhotos(files:FileList|null){if(!files)return;const remaining=Math.max(0,5-photos.length);const chosen=Array.from(files).slice(0,remaining);const compressed=await Promise.all(chosen.map(compressImage));setPhotos(p=>[...p,...compressed].slice(0,5))}
 function compressImage(file:File):Promise<PhotoItem>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(r.error);r.onload=()=>{const img=new Image();img.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);resolve({name:file.name,dataUrl:c.toDataURL('image/jpeg',.72)})};img.onerror=reject;img.src=String(r.result)};r.readAsDataURL(file)})}
 const total=Number(form.total||0),deposit=Math.max(0,Math.min(Number(form.deposit||0),total||Number(form.deposit||0))),due=Math.max(0,total-deposit)
 return <div className="v12-intake-wrap">
  <div className="v11-progress-card v12-progress">{[['1','Client'],['2','Appareil'],['3','Intervention'],['4','Récapitulatif']].map(([n,l],i)=><div key={n} className={`v11-progress-step ${step===i+1?'active':''} ${step>i+1?'done':''}`}><span>{step>i+1?<Check size={15}/>:n}</span><b>{l}</b>{i<3&&<i/>}</div>)}</div>
  <form action="/api/repairs" method="post" className="v11-intake-form-shell">
   <input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="priority" value={priority}/><input type="hidden" name="deviceCategory" value={category}/><input type="hidden" name="notificationChannel" value={contact}/><input type="hidden" name="photoData" value={JSON.stringify(photos.map(p=>p.dataUrl))}/><input type="hidden" name="intakeChecklist" value={JSON.stringify(checks)}/>
   <input type="hidden" name="clientName" value={form.clientName}/><input type="hidden" name="phone" value={form.phone}/><input type="hidden" name="email" value={form.email}/><input type="hidden" name="address" value={form.address}/><input type="hidden" name="postalCode" value={form.postalCode}/><input type="hidden" name="city" value={form.city}/>
   <input type="hidden" name="brand" value={form.brand}/><input type="hidden" name="model" value={form.model}/><input type="hidden" name="deviceColor" value={form.color}/><input type="hidden" name="deviceStorage" value={form.storage}/><input type="hidden" name="imei" value={form.imei}/><input type="hidden" name="lockCode" value={form.lockCode}/><input type="hidden" name="conditionIn" value={form.conditionIn}/><input type="hidden" name="accessories" value={form.accessories}/><input type="hidden" name="powersOn" value={form.powersOn}/><input type="hidden" name="moistureSuspected" value={form.moisture}/>
   <input type="hidden" name="issue" value={form.issue}/><input type="hidden" name="diagnosticNote" value={form.diagnosticNote}/><input type="hidden" name="notes" value={form.notes}/><input type="hidden" name="assignedToId" value={form.assignedToId}/><input type="hidden" name="promisedAt" value={form.promisedAt}/><input type="hidden" name="warrantyDays" value={form.warrantyDays}/>
   <input type="hidden" name="total" value={form.total}/><input type="hidden" name="deposit" value={form.deposit}/><input type="hidden" name="paymentMethod" value={form.paymentMethod}/><input type="hidden" name="signature" value={form.signature}/>
   <input type="hidden" name="diagnosticConsent" value="on"/>{form.backup==='yes'&&<input type="hidden" name="backupConfirmed" value="on"/>}{form.dataAccess==='yes'&&<input type="hidden" name="dataAccessConsent" value="on"/>}{form.quoteRequired==='yes'&&<input type="hidden" name="quoteRequired" value="on"/>}

   {step===1&&<section className="v11-stage card">
    <div className="v11-stage-title"><div className="v11-stage-icon purple"><CircleUserRound size={22}/></div><div><div className="eyebrow">ÉTAPE 1 SUR 4</div><h2>Client & communication</h2><p>Retrouvez une fiche existante ou créez un nouveau client avec ses préférences de contact.</p></div></div>
    {!newClient?<><div className="v11-client-search"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);if(clientId)clearClient()}} placeholder="Rechercher par nom, téléphone ou email…"/><button type="button" onClick={()=>{setNewClient(true);clearClient()}}><UserPlus size={16}/> Nouveau client</button></div><div className="v11-client-results">{filtered.map(c=><button type="button" key={c.id} className={clientId===c.id?'selected':''} onClick={()=>chooseClient(c)}><div className="v11-client-avatar">{c.name.charAt(0).toUpperCase()}</div><div><b>{c.name}</b><small><Phone size={12}/>{c.phone}{c.email?` · ${c.email}`:''}</small></div>{clientId===c.id&&<Check size={18}/>}</button>)}</div></>:<div className="v11-new-client"><div className="v11-inline-head"><h3><UserPlus size={17}/> Nouveau client</h3><button type="button" onClick={()=>setNewClient(false)}>Client existant</button></div><div className="v11-grid two"><label>Nom et prénom *<input value={form.clientName} onChange={e=>set('clientName',e.target.value)} required={!clientId}/></label><label>Téléphone *<input value={form.phone} onChange={e=>set('phone',e.target.value)} required={!clientId}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Adresse<input value={form.address} onChange={e=>set('address',e.target.value)}/></label><label>Code postal<input value={form.postalCode} onChange={e=>set('postalCode',e.target.value)}/></label><label>Ville<input value={form.city} onChange={e=>set('city',e.target.value)}/></label></div></div>}
    {clientId&&<div className="v11-selected-client"><Check size={17}/><div><b>{selected?.name}</b><small>{selected?.phone} · fiche existante</small></div><button type="button" onClick={clearClient}>Changer</button></div>}
    <div className="v11-section-sep"><MessageCircle size={18}/><div><h3>Canal de notification</h3><p>Utilisé pour les mises à jour diagnostic, devis et appareil prêt.</p></div></div>
    <div className="v12-choice-grid four">{([['SMS','SMS',Phone],['WHATSAPP','WhatsApp',MessageCircle],['EMAIL','Email',Mail],['PHONE','Appel',Phone]] as [Contact,string,any][]).map(([k,l,I])=><button type="button" key={k} className={contact===k?'selected':''} onClick={()=>setContact(k)}><I size={18}/><b>{l}</b></button>)}</div>
    <div className="v11-section-sep"><Gauge size={18}/><div><h3>Priorité</h3><p>Ordre de traitement dans le planning atelier.</p></div></div><div className="v11-priority-grid">{(Object.keys(priorityMeta) as Priority[]).map(k=><button type="button" key={k} className={`${priorityMeta[k].className} ${priority===k?'selected':''}`} onClick={()=>setPriority(k)}><span/><b>{priorityMeta[k].label}</b><small>{priorityMeta[k].desc}</small></button>)}</div>
   </section>}

   {step===2&&<section className="v11-stage card">
    <div className="v11-stage-title"><div className="v11-stage-icon blue"><Smartphone size={22}/></div><div><div className="eyebrow">ÉTAPE 2 SUR 4</div><h2>Appareil & état d’entrée</h2><p>Identifiez précisément l’appareil, ses accessoires et son état avant intervention.</p></div></div>
    <div className="v11-section-sep no-border"><Smartphone size={18}/><div><h3>Type d’appareil</h3></div></div><div className="v12-choice-grid six">{cats.map(([k,l,I])=><button type="button" key={k} className={category===k?'selected':''} onClick={()=>setCategory(k)}><I size={19}/><b>{l}</b></button>)}</div>
    {category==='SMARTPHONE'&&<div className="callout" style={{marginBottom:12}}><b>Catalogue smartphones V16</b><div style={{marginTop:4}}>Marques et modèles préchargés pour accélérer la réception. Si un modèle n’est pas encore dans le catalogue, vous pouvez toujours le saisir manuellement.</div></div>}
    <div className="v11-grid three"><label>Marque *<input list={category==='SMARTPHONE'?'smartphone-brands':undefined} value={form.brand} onChange={e=>setForm(v=>({...v,brand:e.target.value,model:''}))} required/>{category==='SMARTPHONE'&&<datalist id="smartphone-brands">{smartphoneBrands.map(b=><option key={b} value={b}/>)}</datalist>}</label><label>Modèle *<input list={category==='SMARTPHONE'?'smartphone-models':undefined} value={form.model} onChange={e=>set('model',e.target.value)} placeholder={category==='SMARTPHONE'?(smartphoneModels.length?'Choisir ou rechercher…':'Saisie libre…'):''} required/>{category==='SMARTPHONE'&&<datalist id="smartphone-models">{smartphoneModels.map(m=><option key={m} value={m}/>)}</datalist>}</label><label>Couleur<input value={form.color} onChange={e=>set('color',e.target.value)}/></label><label>Capacité / stockage<input value={form.storage} onChange={e=>set('storage',e.target.value)} placeholder="128 Go"/></label><label>IMEI / N° série<input value={form.imei} onChange={e=>set('imei',e.target.value)}/></label><label>Code / schéma<input value={form.lockCode} onChange={e=>set('lockCode',e.target.value)}/></label></div>
    <div className="v11-section-sep"><ClipboardCheck size={18}/><div><h3>Contrôle d’entrée</h3><p>Cochez les points présentant une anomalie visible ou signalée.</p></div></div><div className="v12-check-grid">{checklistOptions.map(x=><label key={x}><input type="checkbox" checked={checks.includes(x)} onChange={e=>setChecks(v=>e.target.checked?[...v,x]:v.filter(a=>a!==x))}/><span>{x}</span></label>)}</div>
    <div className="v11-grid two"><label>État esthétique<input value={form.conditionIn} onChange={e=>set('conditionIn',e.target.value)} placeholder="Rayures, choc, vitre cassée…"/></label><label>Accessoires déposés<input value={form.accessories} onChange={e=>set('accessories',e.target.value)} placeholder="Coque, SIM, chargeur…"/></label></div>
    <div className="v12-state-row"><label><Power size={17}/> S’allume ?<select value={form.powersOn} onChange={e=>set('powersOn',e.target.value)}><option value="yes">Oui</option><option value="no">Non</option><option value="unknown">Non testé</option></select></label><label><Droplets size={17}/> Oxydation suspectée ?<select value={form.moisture} onChange={e=>set('moisture',e.target.value)}><option value="no">Non</option><option value="yes">Oui</option></select></label></div>
    <div className="v11-photo-block"><div className="v11-section-sep no-border"><Camera size={18}/><div><h3>Photos avant intervention</h3><p>Jusqu’à 5 photos compressées et enregistrées dans le dossier.</p></div><label className="v11-photo-add"><ImagePlus size={16}/> Ajouter<input type="file" accept="image/*" capture="environment" multiple onChange={e=>addPhotos(e.target.files)}/></label></div>{photos.length?<div className="v11-photo-grid">{photos.map((p,i)=><div key={i}><img src={p.dataUrl} alt="État appareil"/><button type="button" onClick={()=>setPhotos(v=>v.filter((_,x)=>x!==i))}><Trash2 size={14}/></button></div>)}</div>:<div className="v11-photo-empty"><Camera size={24}/><span>Aucune photo</span><small>Recommandé pour protéger l’atelier et le client.</small></div>}</div>
   </section>}

   {step===3&&<section className="v11-stage card">
    <div className="v11-stage-title"><div className="v11-stage-icon purple"><Wrench size={22}/></div><div><div className="eyebrow">ÉTAPE 3 SUR 4</div><h2>Intervention & organisation</h2><p>Décrivez la panne, organisez le diagnostic et encadrez l’accès aux données.</p></div></div>
    <div className="v11-grid two"><label className="span2">Panne / demande *<textarea rows={4} value={form.issue} onChange={e=>set('issue',e.target.value)} required placeholder="Symptômes, demande client, circonstances…"/></label><label className="span2">Pré-diagnostic / observations<textarea rows={3} value={form.diagnosticNote} onChange={e=>set('diagnosticNote',e.target.value)} placeholder="Tests réalisés au comptoir, résultat visuel…"/></label><label className="span2">Notes internes<textarea rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="Informations réservées à l’équipe…"/></label></div>
    <div className="v11-section-sep"><Wrench size={18}/><div><h3>Planification</h3></div></div><div className="v11-grid three"><label>Technicien<select value={form.assignedToId} onChange={e=>set('assignedToId',e.target.value)}><option value="">Attribution automatique</option>{team.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Date promise<input type="datetime-local" value={form.promisedAt} onChange={e=>set('promisedAt',e.target.value)}/></label><label>Garantie prévue (jours)<input type="number" min="0" value={form.warrantyDays} onChange={e=>set('warrantyDays',e.target.value)}/></label></div>
    <div className="v11-section-sep"><ShieldCheck size={18}/><div><h3>Consentements</h3><p>Traçabilité des autorisations données au comptoir.</p></div></div><div className="v12-consent-grid"><label><input type="checkbox" defaultChecked/><div><b>Diagnostic autorisé</b><small>L’atelier peut ouvrir/tester l’appareil pour établir le diagnostic.</small></div></label><label><input type="checkbox" checked={form.backup==='yes'} onChange={e=>set('backup',e.target.checked?'yes':'no')}/><div><b>Sauvegarde confirmée</b><small>Le client confirme avoir sauvegardé ses données importantes.</small></div></label><label><input type="checkbox" checked={form.dataAccess==='yes'} onChange={e=>set('dataAccess',e.target.checked?'yes':'no')}/><div><b>Accès aux données autorisé</b><small>Uniquement si nécessaire pour tester l’appareil.</small></div></label><label><input type="checkbox" checked={form.quoteRequired==='yes'} onChange={e=>set('quoteRequired',e.target.checked?'yes':'no')}/><div><b>Accord avant réparation</b><small>Préparer un devis et attendre l’acceptation avant intervention payante.</small></div></label></div>
   </section>}

   {step===4&&<section className="v11-stage card">
    <div className="v11-stage-title"><div className="v11-stage-icon green"><ClipboardCheck size={22}/></div><div><div className="eyebrow">ÉTAPE 4 SUR 4</div><h2>Récapitulatif, paiement & signature</h2><p>Contrôlez le dossier avant de générer le ticket atelier et le QR de suivi.</p></div></div>
    <div className="v11-recap-grid"><div className="v11-recap-card"><CircleUserRound/><small>CLIENT</small><b>{selected?.name||form.clientName||'—'}</b><span>{selected?.phone||form.phone||'—'}</span></div><div className="v11-recap-card"><Smartphone/><small>APPAREIL</small><b>{form.brand} {form.model}</b><span>{form.color||form.storage?`${form.color} ${form.storage}`:'Identification standard'}</span></div><div className={`v11-recap-card priority ${priorityMeta[priority].className}`}><Gauge/><small>PRIORITÉ</small><b>{priorityMeta[priority].label}</b><span>{priorityMeta[priority].desc}</span></div><div className="v11-recap-card"><Camera/><small>PHOTOS</small><b>{photos.length}</b><span>photo(s) d’état</span></div></div>
    <div className="v11-recap-issue"><small>PANNE / DEMANDE</small><p>{form.issue||'—'}</p>{checks.length>0&&<span>Contrôle : {checks.join(' · ')}</span>}</div>
    <div className="v11-section-sep"><Euro size={18}/><div><h3>Estimation & acompte</h3><p>Le solde reste modifiable depuis la fiche réparation.</p></div></div><div className="v11-grid three"><label>Montant estimé €<input type="number" min="0" step="0.01" value={form.total} onChange={e=>set('total',e.target.value)}/></label><label>Acompte €<input type="number" min="0" step="0.01" value={form.deposit} onChange={e=>set('deposit',e.target.value)}/></label><label>Mode<select value={form.paymentMethod} onChange={e=>set('paymentMethod',e.target.value)}><option value="CARD">Carte</option><option value="CASH">Espèces</option><option value="TRANSFER">Virement</option><option value="OTHER">Autre</option></select></label></div><div className="v11-money-summary"><div><span>Estimation</span><b>{total.toFixed(2)} €</b></div><div><span>Acompte</span><b>{deposit.toFixed(2)} €</b></div><div className="due"><span>Reste estimé</span><b>{due.toFixed(2)} €</b></div></div>
    <div className="v11-signature-box"><FileSignature size={22}/><div><h3>Signature / accord client</h3><p>Le nom du signataire est conservé dans l’historique du dossier.</p></div><label>Nom du signataire<input value={form.signature} onChange={e=>set('signature',e.target.value)} placeholder="Nom et prénom"/></label></div>
    <div className="v11-final-note"><ShieldCheck size={18}/><div><b>Workflow automatique</b><small>Création du dossier + ticket, historique, acompte, photos, QR de suivi et préparation des impressions QZ Tray / Brother.</small></div></div>
   </section>}

   <div className="v11-wizard-actions"><button type="button" className="btn secondary" onClick={()=>step===1?history.back():setStep(step-1)}><ArrowLeft size={16}/>{step===1?'Annuler':'Précédent'}</button><div className="v11-step-hint">Étape {step} / 4</div>{step<4?<button type="button" className="btn v11-next" disabled={!canNext()} onClick={()=>setStep(step+1)}>Suivant <ArrowRight size={17}/></button>:<button type="submit" className="btn v11-submit"><Check size={17}/> Créer la prise en charge</button>}</div>
  </form>
 </div>
}
