'use client'
import {useMemo,useState} from 'react'
import {Minus,Plus,Search,ShoppingCart,Trash2,CreditCard,Banknote,Landmark,ReceiptText} from 'lucide-react'

type Item={id:string;sku:string;name:string;category:string;quantity:number;sellPrice:number}
type CartLine=Item&{qty:number}

export default function PosV15Client({items,maxDiscount,isAdmin}:{items:Item[];maxDiscount:number;isAdmin:boolean}){
 const [q,setQ]=useState('')
 const [cart,setCart]=useState<CartLine[]>([])
 const [discount,setDiscount]=useState(0)
 const [method,setMethod]=useState('CARD')
 const [customerName,setCustomerName]=useState('')
 const [note,setNote]=useState('')
 const [busy,setBusy]=useState(false)
 const [error,setError]=useState('')
 const filtered=useMemo(()=>items.filter(i=>`${i.name} ${i.sku} ${i.category}`.toLowerCase().includes(q.toLowerCase())).slice(0,60),[items,q])
 const subtotal=cart.reduce((s,l)=>s+l.sellPrice*l.qty,0)
 const safeDiscount=Math.min(Math.max(discount,0),maxDiscount)
 const discountAmount=subtotal*safeDiscount/100
 const total=Math.max(0,subtotal-discountAmount)
 function add(i:Item){setCart(c=>{const x=c.find(l=>l.id===i.id);if(x)return c.map(l=>l.id===i.id?{...l,qty:Math.min(l.qty+1,i.quantity)}:l);return [...c,{...i,qty:1}]})}
 function qty(id:string,n:number){setCart(c=>c.map(l=>l.id===id?{...l,qty:Math.max(1,Math.min(n,l.quantity))}:l))}
 async function checkout(){setError('');if(!cart.length)return setError('Ajoutez au moins un article.');if(total<=0)return setError('Le total doit être supérieur à 0.');setBusy(true);try{const res=await fetch('/api/pos/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart.map(l=>({inventoryItemId:l.id,quantity:l.qty})),discountPercent:safeDiscount,paymentMethod:method,customerName,note})});if(!res.ok){setError(await res.text());setBusy(false);return}const data=await res.json();window.location.href=`/pos/receipt/${data.id}`}catch{setError('Erreur lors de l’encaissement.');setBusy(false)}}
 return <div className="posv15-grid">
  <style>{`
   .posv15-grid{display:grid;grid-template-columns:1.35fr .85fr;gap:16px}.posv15-panel{background:#fff;border:1px solid #dce5ef;border-radius:14px;box-shadow:0 8px 24px #20344d0b}.posv15-head{padding:16px;border-bottom:1px solid #edf1f5}.posv15-head h2{font-size:15px;margin:0;color:#17243a}.posv15-search{display:flex;align-items:center;gap:8px;margin-top:10px;border:1px solid #d9e2ec;border-radius:10px;padding:0 11px;height:42px;background:#f9fbfd}.posv15-search input{border:0;outline:0;background:transparent;flex:1}.posv15-products{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:14px;max-height:650px;overflow:auto}.posv15-product{border:1px solid #e0e7ef;border-radius:11px;padding:12px;background:#fbfcfe;text-align:left;cursor:pointer}.posv15-product:hover{border-color:#8eb6e6;background:#f5f9ff}.posv15-product b{display:block;font-size:11px;color:#203149}.posv15-product small{display:block;color:#8592a4;margin-top:3px;font-size:8px}.posv15-product strong{display:block;margin-top:9px;color:#155bb3;font-size:14px}.posv15-cart{padding:14px}.posv15-line{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px 0;border-bottom:1px solid #edf1f5}.posv15-line b{font-size:10px}.posv15-line small{display:block;color:#8b97a8;font-size:8px}.posv15-qty{display:flex;align-items:center;gap:5px}.posv15-qty button{width:27px;height:27px;border:1px solid #dce5ef;background:#fff;border-radius:7px}.posv15-qty input{width:42px;height:27px;border:1px solid #dce5ef;border-radius:7px;text-align:center}.posv15-fields{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px}.posv15-fields label{font-size:8px;font-weight:800;color:#5d6d82}.posv15-fields input,.posv15-fields select{width:100%;height:38px;border:1px solid #d9e2ec;border-radius:9px;padding:0 9px;margin-top:5px;background:#fff}.posv15-total{margin-top:13px;border-top:1px solid #dde5ee;padding-top:10px}.posv15-money{display:flex;justify-content:space-between;padding:5px 0;font-size:10px;color:#68778b}.posv15-money.total{font-size:16px;color:#17243a;font-weight:900}.posv15-pay{width:100%;margin-top:10px;height:44px;border:0;border-radius:10px;background:#1f67c8;color:#fff;font-weight:900;cursor:pointer}.posv15-pay:disabled{opacity:.55}.posv15-error{margin-top:8px;padding:9px;border-radius:8px;background:#fff1f2;color:#b53245;font-size:9px}.posv15-empty{padding:25px;text-align:center;color:#8b97a8;font-size:9px}@media(max-width:1050px){.posv15-grid{grid-template-columns:1fr}.posv15-products{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.posv15-products{grid-template-columns:1fr}.posv15-fields{grid-template-columns:1fr}}
  `}</style>
  <section className="posv15-panel"><div className="posv15-head"><h2>Catalogue & stock</h2><div className="posv15-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher produit, SKU, catégorie…"/></div></div><div className="posv15-products">{filtered.map(i=><button key={i.id} className="posv15-product" onClick={()=>add(i)} disabled={i.quantity<=0}><b>{i.name}</b><small>{i.sku} · {i.category}</small><small>Stock : {i.quantity}</small><strong>{i.sellPrice.toFixed(2)} €</strong></button>)}</div></section>
  <aside className="posv15-panel"><div className="posv15-head"><h2><ShoppingCart size={16}/> Panier de vente</h2></div><div className="posv15-cart">{!cart.length?<div className="posv15-empty">Aucun article dans le panier.</div>:cart.map(l=><div className="posv15-line" key={l.id}><div><b>{l.name}</b><small>{l.sellPrice.toFixed(2)} € × {l.qty} = {(l.sellPrice*l.qty).toFixed(2)} €</small></div><div className="posv15-qty"><button onClick={()=>qty(l.id,l.qty-1)}><Minus size={13}/></button><input type="number" value={l.qty} onChange={e=>qty(l.id,Number(e.target.value)||1)}/><button onClick={()=>qty(l.id,l.qty+1)}><Plus size={13}/></button><button onClick={()=>setCart(c=>c.filter(x=>x.id!==l.id))}><Trash2 size={13}/></button></div></div>)}
   <div className="posv15-fields"><label>Client<input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Nom facultatif"/></label><label>Remise %<input type="number" min="0" max={maxDiscount} step="0.5" value={discount} onChange={e=>setDiscount(Number(e.target.value)||0)}/></label><label>Moyen de paiement<select value={method} onChange={e=>setMethod(e.target.value)}><option value="CARD">Carte</option><option value="CASH">Espèces</option><option value="TRANSFER">Virement</option><option value="OTHER">Autre</option></select></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Référence, commentaire…"/></label></div>
   <div className="posv15-total"><div className="posv15-money"><span>Sous-total</span><b>{subtotal.toFixed(2)} €</b></div><div className="posv15-money"><span>Remise ({safeDiscount.toFixed(1)}%)</span><b>- {discountAmount.toFixed(2)} €</b></div><div className="posv15-money total"><span>Total</span><b>{total.toFixed(2)} €</b></div></div>
   <button className="posv15-pay" onClick={checkout} disabled={busy||!cart.length}>{busy?'Encaissement…':method==='CASH'?<><Banknote size={16}/> Encaisser en espèces</>:method==='CARD'?<><CreditCard size={16}/> Encaisser par carte</>:method==='TRANSFER'?<><Landmark size={16}/> Valider le virement</>:<><ReceiptText size={16}/> Valider la vente</>}</button>{error&&<div className="posv15-error">{error}</div>}<div style={{marginTop:8,fontSize:8,color:'#8b97a8'}}>Remise autorisée : jusqu’à {maxDiscount}% {isAdmin?'(administrateur)':'(technicien)'}</div>
  </div></aside>
 </div>
}
