import Link from 'next/link'
import {redirect} from 'next/navigation'
import AppShell from '@/components/AppShell'
import {getSession} from '@/lib/auth'
import {prisma} from '@/lib/prisma'
import {eur,dateFr} from '@/lib/format'
import {Monitor,WalletCards,LockKeyhole,UnlockKeyhole,ArrowDownCircle,ArrowUpCircle,ReceiptText,Printer,Clock3,Scale,Landmark,Coins,TriangleAlert,UserRoundCog,ShieldCheck} from 'lucide-react'

function sum<T>(items:T[],pick:(v:T)=>number){return items.reduce((a,v)=>a+pick(v),0)}

export default async function Page(){
 const s=await getSession();if(!s)redirect('/login')
 const isAdmin=s.role==='ADMIN'
 const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1)
 const [current,history,dayPayments,activeUsers]=await Promise.all([
  prisma.cashSession.findFirst({where:{status:'OPEN'},orderBy:{openedAt:'desc'},include:{openedBy:true,movements:{orderBy:{createdAt:'desc'}},payments:{include:{repair:{include:{client:true}}},orderBy:{createdAt:'desc'}}}}),
  prisma.cashSession.findMany({where:{status:'CLOSED'},take:15,orderBy:{closedAt:'desc'},include:{openedBy:true}}),
  prisma.payment.findMany({where:{createdAt:{gte:start,lt:end}},include:{repair:{include:{client:true}}},orderBy:{createdAt:'desc'}}),
  prisma.user.findMany({where:{active:true},orderBy:{name:'asc'},select:{id:true,name:true,role:true}})
 ])
 const cashSales=current?sum(current.payments.filter(p=>p.method==='CASH'),p=>Number(p.amount)):0
 const cardSales=current?sum(current.payments.filter(p=>p.method==='CARD'),p=>Number(p.amount)):0
 const transferSales=current?sum(current.payments.filter(p=>p.method==='TRANSFER'),p=>Number(p.amount)):0
 const otherSales=current?sum(current.payments.filter(p=>p.method==='OTHER'),p=>Number(p.amount)):0
 const movements=current?.movements.filter(m=>!['OPENING','CLOSING'].includes(m.type))||[]
 const extras=sum(movements,m=>Number(m.amount))
 const expenses=Math.abs(sum(movements.filter(m=>Number(m.amount)<0),m=>Number(m.amount)))
 const adjustments=sum(movements.filter(m=>m.type==='ADJUSTMENT'),m=>Number(m.amount))
 const expected=(current?Number(current.openingAmount):0)+cashSales+extras
 const sessionTurnover=cashSales+cardSales+transferSales+otherSales
 const todayCash=sum(dayPayments.filter(p=>p.method==='CASH'),p=>Number(p.amount))
 const todayCard=sum(dayPayments.filter(p=>p.method==='CARD'),p=>Number(p.amount))
 const todayTransfer=sum(dayPayments.filter(p=>p.method==='TRANSFER'),p=>Number(p.amount))
 const todayOther=sum(dayPayments.filter(p=>p.method==='OTHER'),p=>Number(p.amount))
 const todayTotal=todayCash+todayCard+todayTransfer+todayOther
 const closedWithDiff=history.filter(h=>h.expectedAmount!=null&&h.closingAmount!=null)
 const diffTotal=sum(closedWithDiff,h=>Number(h.closingAmount)-Number(h.expectedAmount))
 const lastDiff=closedWithDiff[0]?Number(closedWithDiff[0].closingAmount)-Number(closedWithDiff[0].expectedAmount):0
 return <AppShell>
  <div className="cash-pro">
   <style>{`
    .cash-pro{max-width:1500px;margin:0 auto;color:#17243a}.cash-pro *{box-sizing:border-box}.cash-pro .pro-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;padding:2px 0 20px;border-bottom:1px solid #e1e8f0;margin-bottom:16px}.cash-pro .eyebrow{font-size:8px;letter-spacing:1.6px;font-weight:900;color:#738197}.cash-pro h1{font-size:30px;letter-spacing:-1px;margin:4px 0 5px;color:#132238}.cash-pro .sub{font-size:10px;color:#8794a6;margin:0;max-width:680px}.cash-pro .actions{display:flex;gap:7px;flex-wrap:wrap}.cash-pro .actions .btn{background:#fff;color:#33445b;border:1px solid #d9e3ed;border-radius:9px;box-shadow:0 3px 10px rgba(30,50,75,.04);font-size:9px}.cash-pro .actions .btn:hover{border-color:#abc4df;transform:translateY(-1px)}
    .cash-pro .statusbar{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 13px;border:1px solid #dce6f0;border-radius:11px;background:#fff;margin-bottom:12px}.cash-pro .status-left{display:flex;align-items:center;gap:9px;font-size:9px;color:#65758a}.cash-pro .dot{width:8px;height:8px;border-radius:50%;background:#20a36f;box-shadow:0 0 0 4px #20a36f18}.cash-pro .statusbar b{color:#26374d}.cash-pro .status-right{font-size:9px;color:#77869a}.cash-pro .status-right strong{color:#17243a;font-size:12px;margin-left:5px}
    .cash-pro .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.cash-pro .kpi{position:relative;padding:15px;border:1px solid #dce5ef;border-radius:12px;background:#fff;box-shadow:0 6px 18px rgba(30,50,75,.045);min-height:105px}.cash-pro .kpi:after{content:'';position:absolute;right:0;top:0;width:4px;height:100%;background:#dfe8f2;border-radius:0 12px 12px 0}.cash-pro .kpi:nth-child(1):after{background:#2e75d6}.cash-pro .kpi:nth-child(2):after{background:#20a36f}.cash-pro .kpi:nth-child(3):after{background:#7555c9}.cash-pro .kpi:nth-child(4):after{background:#e28a21}.cash-pro .kpi-top{display:flex;align-items:center;justify-content:space-between}.cash-pro .kpi-icon{width:33px;height:33px;border-radius:9px;display:grid;place-items:center;background:#edf5ff;color:#2e75d6}.cash-pro .kpi:nth-child(2) .kpi-icon{background:#ebfaf3;color:#20a36f}.cash-pro .kpi:nth-child(3) .kpi-icon{background:#f2effc;color:#7555c9}.cash-pro .kpi:nth-child(4) .kpi-icon{background:#fff4e6;color:#df871d}.cash-pro .kpi small{display:block;font-size:8px;font-weight:900;letter-spacing:.45px;color:#718095;margin-top:10px}.cash-pro .kpi strong{display:block;font-size:21px;letter-spacing:-.5px;color:#17243a;margin-top:2px}.cash-pro .kpi em{font-style:normal;font-size:8px;color:#95a0af}
    .cash-pro .panel{background:#fff;border:1px solid #dce5ef;border-radius:12px;box-shadow:0 6px 18px rgba(30,50,75,.035);padding:16px}.cash-pro .panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:13px}.cash-pro .panel-head h2{font-size:14px;color:#1b2c43;margin:0;display:flex;align-items:center;gap:7px}.cash-pro .panel-head p{font-size:9px;color:#8a97a8;margin:4px 0 0}.cash-pro .badge{border-radius:999px;padding:6px 9px;font-size:8px;font-weight:900}.cash-pro .open{background:#eaf9f1;color:#159668;border:1px solid #cbe9d9}.cash-pro .locked{background:#fff3e4;color:#d87918;border:1px solid #f1d8b7}.cash-pro .session-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:10px}.cash-pro .mini-card{border:1px solid #e3e9f0;border-radius:10px;padding:13px;background:#fbfcfe}.cash-pro .mini-card h3{font-size:10px;margin:0 0 8px;color:#3c4c61}.cash-pro .money{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #edf1f5;font-size:9px;color:#738196}.cash-pro .money:last-child{border-bottom:0}.cash-pro .money strong{color:#1b2b42}.cash-pro .money.total{margin-top:4px;border-top:1px solid #dce5ee;padding-top:11px;font-size:10px;color:#33445a}.cash-pro .money.total strong{font-size:13px}.cash-pro .two-cols{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cash-pro .warn{display:flex;gap:9px;align-items:flex-start;padding:10px;border:1px solid #f0dfc6;background:#fff9f1;border-radius:9px;color:#72511f;font-size:9px}.cash-pro .warn small{display:block;color:#9a8668;margin-top:2px}.cash-pro .form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cash-pro label{display:flex;flex-direction:column;gap:5px;font-size:9px;font-weight:800;color:#536278}.cash-pro input,.cash-pro select{width:100%;height:38px;background:#fbfcfe;border:1px solid #d8e2ec;border-radius:8px;padding:0 10px;color:#24354b;outline:none;font-size:10px}.cash-pro input:focus,.cash-pro select:focus{border-color:#8fb2d7;box-shadow:0 0 0 3px #5d9add14}.cash-pro .span2{grid-column:1/-1}.cash-pro .btn.primary{background:#246dcc;color:#fff;border:0;box-shadow:0 7px 16px #246dcc22}.cash-pro .btn.primary:hover{filter:brightness(1.04)}
    .cash-pro table th{background:#f7f9fc;color:#738197;font-size:8px;letter-spacing:.5px;border-bottom:1px solid #e0e7ef;padding:10px}.cash-pro table td{font-size:9px;color:#405169;border-bottom:1px solid #edf1f5;padding:10px}.cash-pro table tbody tr:hover{background:#f9fbfd}.cash-pro .row-link{color:#246dcc;font-weight:900}.cash-pro .green{color:#159668}.cash-pro .red{color:#d94a59}.cash-pro .muted{color:#8b98a8;font-size:9px}.cash-pro .empty{min-height:90px;color:#8a97a8;display:grid;place-items:center;font-size:9px}.cash-pro .history-summary{display:flex;align-items:center;gap:20px}.cash-pro .history-summary small{display:block;color:#8b98a8;font-size:8px}.cash-pro .history-summary strong{font-size:13px;color:#17243a}.cash-pro .section-gap{margin-top:12px}
    @media(max-width:1050px){.cash-pro .kpis{grid-template-columns:repeat(2,1fr)}.cash-pro .pro-head{align-items:flex-start;flex-direction:column}.cash-pro .session-grid,.cash-pro .two-cols{grid-template-columns:1fr}}
    @media(max-width:620px){.cash-pro .kpis,.cash-pro .form-grid{grid-template-columns:1fr}.cash-pro .actions{width:100%}.cash-pro .actions .btn{flex:1}.cash-pro h1{font-size:25px}.cash-pro .statusbar{align-items:flex-start;flex-direction:column}}
   `}</style>

   <div className="pro-head"><div><div className="eyebrow">FINANCE · POS · CONTRÔLE INTERNE · V14</div><h1>Caisse & finances</h1><p>Pilotage des encaissements, du tiroir, des opérateurs et des clôtures avec une lecture financière claire.</p></div><div className="actions"><Link className="btn secondary" href="/cash/report"><Printer size={15}/> Rapport X / Z</Link><Link className="btn secondary" href="/cash/report/thermal"><ReceiptText size={15}/> Ticket Z</Link><Link className="btn secondary" href="/settings/print"><Printer size={15}/> Impression</Link></div></div>

   {current?<div className="statusbar"><div className="status-left"><span className="dot"/><span><b>Caisse ouverte</b> · opérateur {current.openedBy.name} · {dateFr(current.openedAt)}</span></div><div className="status-right">Espèces théoriques <strong>{eur(expected)}</strong></div></div>:<div className="statusbar"><div className="status-left"><span className="dot" style={{background:'#e28a21',boxShadow:'0 0 0 4px #e28a2118'}}/><span><b>Caisse fermée</b> · aucune session active</span></div><div className="status-right">Encaissements du jour <strong>{eur(todayTotal)}</strong></div></div>}

   <div className="kpis section-gap">
    <div className="kpi"><div className="kpi-top"><span className="kpi-icon"><Coins size={17}/></span><em>{dayPayments.length} opération(s)</em></div><small>ENCAISSEMENTS DU JOUR</small><strong>{eur(todayTotal)}</strong><em>tous moyens de paiement</em></div>
    <div className="kpi"><div className="kpi-top"><span className="kpi-icon"><Monitor size={17}/></span><em>espèces</em></div><small>ESPÈCES DU JOUR</small><strong>{eur(todayCash)}</strong><em>flux espèces enregistrés</em></div>
    <div className="kpi"><div className="kpi-top"><span className="kpi-icon"><WalletCards size={17}/></span><em>CB / TPE</em></div><small>PAIEMENTS CARTE</small><strong>{eur(todayCard)}</strong><em>encaissements carte</em></div>
    <div className="kpi"><div className="kpi-top"><span className="kpi-icon"><Landmark size={17}/></span><em>hors espèces</em></div><small>VIREMENTS & AUTRES</small><strong>{eur(todayTransfer+todayOther)}</strong><em>autres moyens</em></div>
   </div>

   {!current?<section className="panel section-gap"><div className="panel-head"><div><h2><UnlockKeyhole size={17}/> Ouvrir la caisse</h2><p>Définissez le fond initial avant les opérations espèces.</p></div>{!isAdmin&&<span className="badge locked">ADMIN REQUIS</span>}</div>{isAdmin?<form action="/api/cash/open" method="post" className="form-grid"><label>Fond de caisse €<input name="openingAmount" type="number" step="0.01" min="0" defaultValue="100"/></label><label>Note d’ouverture<input name="note" placeholder="Ouverture matin / équipe"/></label><div className="span2"><button className="btn primary"><UnlockKeyhole size={15}/> Ouvrir la session</button></div></form>:<div className="warn"><ShieldCheck size={16}/><div><b>Ouverture réservée à l’administrateur.</b><small>La consultation reste disponible pour les techniciens.</small></div></div>}</section>:<>
    <section className="panel section-gap"><div className="panel-head"><div><h2><Clock3 size={17}/> Session en cours</h2><p>Vue de contrôle de la session active et du tiroir.</p></div><span className="badge open">OUVERTE</span></div>
     <div className="kpis"><div className="kpi"><div className="kpi-top"><span className="kpi-icon"><Monitor size={17}/></span></div><small>ESPÈCES ATTENDUES</small><strong>{eur(expected)}</strong><em>fond + ventes espèces + mouvements</em></div><div className="kpi"><div className="kpi-top"><span className="kpi-icon"><ArrowUpCircle size={17}/></span></div><small>CA SESSION</small><strong>{eur(sessionTurnover)}</strong><em>tous moyens de paiement</em></div><div className="kpi"><div className="kpi-top"><span className="kpi-icon"><ArrowDownCircle size={17}/></span></div><small>SORTIES</small><strong>{eur(expenses)}</strong><em>dépenses et remboursements</em></div><div className="kpi"><div className="kpi-top"><span className="kpi-icon"><Scale size={17}/></span></div><small>AJUSTEMENTS</small><strong>{eur(adjustments)}</strong><em>corrections manuelles</em></div></div>
     <div className="session-grid section-gap"><div className="mini-card"><h3>Répartition des encaissements</h3><div className="money"><span>Espèces</span><strong>{eur(cashSales)}</strong></div><div className="money"><span>Carte</span><strong>{eur(cardSales)}</strong></div><div className="money"><span>Virement</span><strong>{eur(transferSales)}</strong></div><div className="money"><span>Autres</span><strong>{eur(otherSales)}</strong></div><div className="money total"><span>Total session</span><strong>{eur(sessionTurnover)}</strong></div></div><div className="mini-card"><h3>Rapprochement du tiroir</h3><div className="money"><span>Fond initial</span><strong>{eur(Number(current.openingAmount))}</strong></div><div className="money"><span>Ventes espèces</span><strong>{eur(cashSales)}</strong></div><div className="money"><span>Mouvements nets</span><strong>{eur(extras)}</strong></div><div className="money total"><span>Espèces théoriques</span><strong>{eur(expected)}</strong></div></div></div>
    </section>

    {isAdmin&&<section className="panel section-gap"><div className="panel-head"><div><h2><UserRoundCog size={17}/> Opérateur de caisse</h2><p>Changez l’opérateur actif sans fermer la session.</p></div></div><form action="/api/cash/cashier" method="post" className="two-cols"><select name="userId" defaultValue={current.openedById}>{activeUsers.map(u=><option key={u.id} value={u.id}>{u.name} · {u.role==='ADMIN'?'Administrateur':'Technicien'}</option>)}</select><button className="btn secondary">Activer cet opérateur</button></form></section>}

    <div className="two-cols section-gap"><section className="panel"><div className="panel-head"><div><h2><ArrowDownCircle size={17}/> Mouvement manuel</h2><p>Dépense, remboursement ou ajustement du tiroir.</p></div>{!isAdmin&&<span className="badge locked">LECTURE SEULE</span>}</div>{isAdmin?<form action="/api/cash/movement" method="post" className="form-grid"><label>Type<select name="type"><option value="EXPENSE">Dépense / sortie</option><option value="REFUND">Remboursement</option><option value="ADJUSTMENT">Ajustement +/-</option></select></label><label>Montant €<input name="amount" type="number" step="0.01" required/></label><label>Libellé<input name="label" required placeholder="Fournitures, retrait, correction…"/></label><label>Note<input name="note" placeholder="Motif / justificatif"/></label><div className="span2"><button className="btn secondary">Enregistrer le mouvement</button></div></form>:<div className="muted">Les mouvements sont réservés à l’administrateur.</div>}</section>
     <section className="panel"><div className="panel-head"><div><h2><LockKeyhole size={17}/> Clôture & rapprochement</h2><p>Le comptage réel permet de conserver l’écart de caisse.</p></div></div><div className="warn"><TriangleAlert size={16}/><div><b>Théorique : {eur(expected)}</b><small>Comptez physiquement le tiroir avant la clôture.</small></div></div>{isAdmin?<form action="/api/cash/close" method="post" className="form-grid section-gap"><label>Comptage réel €<input name="closingAmount" type="number" step="0.01" min="0" required/></label><label>Note de clôture<input name="note" placeholder="Écart expliqué, retrait banque…"/></label><div className="span2"><button className="btn primary"><LockKeyhole size={15}/> Clôturer et calculer l’écart</button></div></form>:<div className="muted section-gap">Clôture réservée à l’administrateur.</div>}</section></div>

    <section className="panel section-gap"><div className="panel-head"><div><h2>Encaissements de la session</h2><p>Derniers paiements rattachés aux dossiers atelier.</p></div><strong>{current.payments.length}</strong></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Dossier</th><th>Client</th><th>Moyen</th><th>Montant</th></tr></thead><tbody>{current.payments.map(p=><tr key={p.id}><td>{dateFr(p.createdAt)}</td><td><Link className="row-link" href={`/repairs/${p.repairId}`}>TKT-{String(p.repair.ticketNo).padStart(5,'0')}</Link></td><td>{p.repair.client.name}</td><td>{p.method==='CASH'?'Espèces':p.method==='CARD'?'Carte':p.method==='TRANSFER'?'Virement':'Autre'}</td><td><b>{eur(Number(p.amount))}</b></td></tr>)}</tbody></table></div>{!current.payments.length&&<div className="empty">Aucun encaissement dans cette session.</div>}</section>
    <section className="panel section-gap"><div className="panel-head"><div><h2>Mouvements du tiroir</h2><p>Dépenses, remboursements et ajustements.</p></div><strong>{current.movements.length}</strong></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Libellé</th><th>Note</th><th>Montant</th></tr></thead><tbody>{current.movements.map(m=><tr key={m.id}><td>{dateFr(m.createdAt)}</td><td>{m.type}</td><td>{m.label}</td><td>{m.note||'—'}</td><td><b>{eur(Number(m.amount))}</b></td></tr>)}</tbody></table></div></section>
   </>}

   <section className="panel section-gap"><div className="panel-head"><div><h2>Historique des clôtures</h2><p>Suivi des écarts des dernières sessions.</p></div><div className="history-summary"><div><small>Écart cumulé</small><strong>{eur(diffTotal)}</strong></div><div><small>Dernier écart</small><strong className={lastDiff===0?'green':Math.abs(lastDiff)<=2?'':'red'}>{eur(lastDiff)}</strong></div></div></div><div className="table-wrap"><table><thead><tr><th>Ouverture</th><th>Clôture</th><th>Utilisateur</th><th>Fond</th><th>Attendu</th><th>Compté</th><th>Écart</th></tr></thead><tbody>{history.map(h=>{const d=Number(h.closingAmount||0)-Number(h.expectedAmount||0);return <tr key={h.id}><td>{dateFr(h.openedAt)}</td><td>{h.closedAt?dateFr(h.closedAt):'—'}</td><td>{h.openedBy.name}</td><td>{eur(Number(h.openingAmount))}</td><td>{eur(Number(h.expectedAmount||0))}</td><td>{eur(Number(h.closingAmount||0))}</td><td><b className={d===0?'green':Math.abs(d)<=2?'':'red'}>{eur(d)}</b></td></tr>})}</tbody></table></div>{!history.length&&<div className="empty">Aucune clôture enregistrée.</div>}</section>
  </div>
 </AppShell>
}
