import { notFound,redirect } from 'next/navigation'
import Link from 'next/link'
import AppShell from '@/components/AppShell'
import PrintPageButton from '@/components/PrintPageButton'
import { getSession } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { eur,dateFr,paymentLabel } from '@/lib/format'
import { ArrowLeft } from 'lucide-react'
export default async function InvoicePage({params}:{params:Promise<{id:string}>}){if(!(await getSession()))redirect('/login');const {id}=await params;const i=await prisma.invoice.findUnique({where:{id},include:{repair:{include:{client:true,payments:true}}}});if(!i)notFound();const paid=i.repair.payments.reduce((a,p)=>a+Number(p.amount),0);return <AppShell><div className="detail-top no-print"><Link className="back" href="/invoices"><ArrowLeft size={17}/> Retour factures</Link><PrintPageButton label="Imprimer la facture"/></div><article className="invoice-sheet"><header><div><div className="invoice-brand">LUXURY <span>PHONE</span></div><p>Centre de réparation</p></div><div className="invoice-no"><small>FACTURE</small><strong>F-{i.invoiceNo}</strong><span>{dateFr(i.issuedAt)}</span></div></header><div className="invoice-meta"><div><small>FACTURÉ À</small><h3>{i.repair.client.name}</h3><p>{i.repair.client.phone}<br/>{i.repair.client.email||''}</p></div><div><small>DOSSIER ATELIER</small><h3>#{i.repair.ticketNo}</h3><p>{i.repair.deviceBrand} {i.repair.deviceModel}<br/>{i.repair.imei||''}</p></div></div><table className="invoice-table"><thead><tr><th>Description</th><th>Montant</th></tr></thead><tbody><tr><td><b>Réparation {i.repair.deviceBrand} {i.repair.deviceModel}</b><small>{i.repair.issue}</small>{i.repair.workDone&&<small>Travaux : {i.repair.workDone}</small>}</td><td>{eur(Number(i.repair.total))}</td></tr></tbody></table><div className="invoice-totals"><div><span>Total</span><b>{eur(Number(i.repair.total))}</b></div><div><span>Déjà réglé</span><b>{eur(paid)}</b></div><div className="grand"><span>Reste dû</span><b>{eur(Math.max(0,Number(i.repair.total)-paid))}</b></div></div>{i.repair.payments.length>0&&<div className="invoice-payments"><small>RÈGLEMENTS</small>{i.repair.payments.map(p=><p key={p.id}>{dateFr(p.createdAt)} · {paymentLabel[p.method]} · {eur(Number(p.amount))}</p>)}</div>}<footer>Merci pour votre confiance · Luxury Phone</footer></article></AppShell>}
